[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1XxQq87OUVUSbVrMu2e5DTag38RO97bXz-LxGYIhvc7g/edit"
gas_url = "https://script.google.com/macros/s/AKfycbzRq0xXwe2sTwtP3lKk6EAxPA2AVF6f7P1fG7_WsgLvptjHVsLtjq_2b-ngivBv-LyN/exec"